language: scala
scala:
  - 2.11.8
  - 2.12.0
  - 2.12.1
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
